# Generated by Django 5.1.5 on 2025-01-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_ride_pickup_location_lat_ride_pickup_location_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='current_location_lat',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='current_location_lon',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_location_lat',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_location_lon',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
    ]
