# Generated by Django 5.1.5 on 2025-01-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_lat_user_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='long',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=20),
        ),
    ]
